version: '3.8'

services:
  app:
    image: laravelphp/php-fpm:latest
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:x2+i1kTIkgZ+QG8ovAFk3eiq9v2/1pq5KRs1zktRfNo=
      APP_DEBUG: "true"
      APP_URL: http://localhost
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ExamenComplexivo
      DB_USERNAME: root
      DB_PASSWORD: "root"
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: hello@example.com
      MAIL_FROM_NAME: Laravel
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db

  nginx:
    image: nginx:1.29
    container_name: nginx_laravel
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ExamenComplexivo
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

volumes:
  dbdata:
