version: '3.8'

services:
  # Servicio de la aplicación (PHP-FPM)
  app:
    image: crisacalo/examen_complexivo:latest
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      # Compartimos el código de la aplicación a través de un volumen con nombre
      - code:/var/www/html
      # Aún montamos el .env para poder configurarlo externamente
      - ./.env:/var/www/html/.env
    networks:
      - laravel

  # Servicio del servidor web (Nginx)
  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      # Montamos el mismo volumen con nombre para que Nginx pueda leer los archivos
      - code:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  # Servicio de la base de datos (MySQL)
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ExamenComplexivo
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33066:3306"
    networks:
      - laravel

# Definición de la red y los volúmenes
networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
  # Definimos el nuevo volumen para compartir el código
  code:
    driver: local
