version: '3.8'

services:
    app:
        image: crisacalo/examen_complexivo:latest
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - code:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: laravel_web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - code:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ExamenComplexivo
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "33066:3306"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
    code:
        driver: local
